name: dev apk build
on:
  push:
    branches: [ master ]
jobs:
  build_job:
    name: build apk job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk
      - uses: its404/get-flutter-version@v1.0.0
        id: get_version
      - uses: 1466587594/get-current-time@v2
        id: get_time
        with:
          format: YYYYMMDD.HHmmss
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          tag: v${{steps.get_version.outputs.version_number}}_beta_${{steps.get_time.outputs.formattedTime}}
          body: "auto release when push"
          artifacts: "build/app/outputs/apk/release/*.apk"
          prerelease: true
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tags: true
          delete_tag_pattern: _beta_
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

