name: build actions
on:
  push:
    branches: [ master ]
jobs:
  build_job:
    name: build apk job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk